#!/bin/bash
#
#created 2/15/2015 
#script to apply skull stripping to participant's T1s with suboptimal skull stripping results from the bet parameter -f 0.35. 
#input images are the results from the initial bwFnirtBot output (prior to skull stripping) after reorientation to RPI
#
#
#
# bet paramter -f "fractional intensity threshold" default=0.5; smaller values
# give larger brain outline estimates#bet parameter -B attempts to reduce image
# bias and residual neck voxels
betOpts="-f 0.30 -B"
#
#
#
for blind in 10 12 14 20 21 22 23 25 27 28 29 31 33 35 36 38 39 41 44 46 49 52 53 55 56 58 62 65 66 67 70 74 76 79 ; do

	bet /data/birc/Atlanta/tranThesis/03.derivedData/brainExtractT1/20150211_bwFnirtBotOutput/inNativeSpaceOfT1/betMA0${blind}_t1.nii.gz /data/birc/Atlanta/tranThesis/03.derivedData/brainExtractT1/20150215_betF30/betMA0${blind}_t1_brain ${betOpts}  

done
